calcom:
  postgresql:
    enabled: false

global:
  netpol:
    enabled: false
  calcom:
    netpol: false

  postgresql:
    enabled: true
    monitoring:
      enablePodMonitor: true
    instanceName: calcom
    instances: 1
    backups:
      enabled: false
      schedule: "0 2 * * *"
      retentionPolicy: 30d
      provider: aws
      aws:
        enableKube2IAMIntegration: true
    logicalbackup:
      enabled: false
      schedule: "0 2 * * *"
      provider: s3
      retention: "30d"
